default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tcb_live_development
  username: postgres
  password: password
  host: db

test:
  <<: *default
  database: tcb_live_test
  username: postgres
  password: password
  host: db
  pool: 20

production:
  primary: &primary_production
    <<: *default
    database: tcb_live_production
    username: tcb_live
    url: <%= ENV['DATABASE_URL'] %>
    # password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tcb_live_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tcb_live_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tcb_live_production_cable
    migrations_paths: db/cable_migrate