name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: tcb_live_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports: ['6379:6379']

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub" >> $GITHUB_ENV

      - name: Build all containers (including selenium)
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for Selenium
        run: |
          echo "Waiting for Selenium to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "Selenium is ready!"
              break
            fi
            sleep 2
          done

      - name: Run DB setup
        run: docker compose exec -T web bundle exec rails db:prepare

      - name: Run RSpec (including browser tests)
        run: docker compose exec -T web bundle exec rspec
