name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "RAILS_ENV=test" >> $GITHUB_ENV
          echo "SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub" >> $GITHUB_ENV

      - name: Build containers for CI
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d --build

      - name: Wait for Selenium
        run: |
          echo "Waiting for Selenium to be ready..."
          for i in {1..20}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "Selenium is ready!"
              break
            fi
            sleep 2
          done

      - name: Run DB setup
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml exec -T web bundle exec rails db:prepare

      - name: Run RSpec
        run: docker compose -f docker-compose.yml -f docker-compose.ci.yml exec -T web bundle exec rspec
